[workspace]
resolver = "2"

members = [
    "day*",
]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
must_use_candidate = { level = "allow", priority = 1 }
cast_possible_wrap = { level = "allow", priority = 1 }
